package on2016_10.on2016_10_18_Codeforces_Round__377__Div__2_.D___Exams;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2016_10/on2016_10_18_Codeforces_Round__377__Div__2_/D___Exams/D - Exams.task"))
			Assert.fail();
	}
}
